#include "GFC600_utils.h"

Rect activeLateralArea = {0, 0, WIDTH_LATERAL - CORRECTION_FACTOR, CLEAR_HEIGHT};
Rect armedLateralArea = {0, Y_ARMED - CORRECTION_FACTOR * 3, WIDTH_LATERAL - CORRECTION_FACTOR, CLEAR_HEIGHT};
Rect activeVerticalArea = {X_DIV1 + CORRECTION_FACTOR, 0, WIDTH_VERTICAL - CORRECTION_FACTOR, CLEAR_HEIGHT};
Rect armedVerticalArea = {X_DIV1 + CORRECTION_FACTOR, Y_ARMED - CORRECTION_FACTOR * 3, WIDTH_VERTICAL - CORRECTION_FACTOR, CLEAR_HEIGHT};
